# Generated by Django 4.1 on 2022-09-12 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0002_alter_noticia_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='autor',
            new_name='autor_nombre',
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
