# Generated by Django 4.1 on 2022-09-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_alter_noticia_cuerpo'),
        ('AppBlog', '0006_remove_usuario_contraseña1_and_more'),
    ]

    operations = [
    ]
