# Generated by Django 4.1 on 2022-09-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_usuario_id_alter_usuario_nombre_de_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_de_usuario',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
