# Generated by Django 4.1 on 2022-09-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0014_noticia_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
