# Generated by Django 4.1 on 2022-09-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0004_alter_mensaje_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='is_read',
        ),
    ]
