# Generated by Django 4.1 on 2022-09-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_remove_noticia_autor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('nombre_de_usuario', models.CharField(max_length=80)),
                ('contraseña1', models.CharField(max_length=20)),
                ('contraseña2', models.CharField(max_length=20)),
            ],
        ),
    ]
