# Generated by Django 4.1 on 2022-09-12 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0004_remove_noticia_autor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autor_nombre',
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=models.TextField(),
        ),
    ]
