# Generated by Django 4.1 on 2022-09-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña2',
        ),
    ]
