# Generated by Django 4.1 on 2022-09-13 16:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_remove_noticia_autor_nombre_noticia_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
