# Generated by Django 4.1 on 2022-09-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0008_categoria_noticia_categoria'),
        ('AppBlog', '0011_usuario_id_alter_usuario_nombre_de_usuario'),
    ]

    operations = [
    ]
