# Generated by Django 4.1 on 2022-09-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0013_alter_categoria_nombre_alter_noticia_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
