# Generated by Django 4.1 on 2022-09-19 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0014_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='likes',
            field=models.ManyToManyField(related_name='noticia_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
