# Generated by Django 4.1 on 2022-09-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0018_alter_comentario_texto"),
        ("AppBlog", "0020_alter_avatar_imagen"),
    ]

    operations = []
