# Generated by Django 4.1 on 2022-09-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0021_merge_20220925_1755"),
        ("AppBlog", "0021_merge_20220925_2206"),
        ("AppBlog", "0021_merge_20220925_2230"),
    ]

    operations = []
