# Generated by Django 4.1 on 2022-09-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0022_merge_20220925_2337'),
        ('AppBlog', '0022_merge_20220926_1224'),
    ]

    operations = [
    ]
