# Generated by Django 4.1 on 2022-09-27 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0022_merge_20220926_1007"),
        ("AppBlog", "0023_merge_20220926_1254"),
    ]

    operations = []
