# Generated by Django 4.1 on 2022-09-26 00:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0002_alter_mensaje_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=1500),
        ),
    ]
