# Generated by Django 4.1 on 2022-09-26 01:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0003_alter_mensaje_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
